// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCut82dAtrJeeHzY54NJe8VOYLgO7oOF6E',
    appId: '1:552256631901:web:31bf216b76a844b79949b4',
    messagingSenderId: '552256631901',
    projectId: 'healthapp-b2092',
    authDomain: 'healthapp-b2092.firebaseapp.com',
    storageBucket: 'healthapp-b2092.firebasestorage.app',
    measurementId: 'G-X2XPPLE1DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBIpYXbgN8ujCF6_R6d3C1oYrilX3-VQ',
    appId: '1:552256631901:android:c50443e46a35e0b59949b4',
    messagingSenderId: '552256631901',
    projectId: 'healthapp-b2092',
    storageBucket: 'healthapp-b2092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO7FjiRN7_8RqWT8QHjFsDA4fbxH7hWk',
    appId: '1:552256631901:ios:e69954dbc573fd309949b4',
    messagingSenderId: '552256631901',
    projectId: 'healthapp-b2092',
    storageBucket: 'healthapp-b2092.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRO7FjiRN7_8RqWT8QHjFsDA4fbxH7hWk',
    appId: '1:552256631901:ios:e69954dbc573fd309949b4',
    messagingSenderId: '552256631901',
    projectId: 'healthapp-b2092',
    storageBucket: 'healthapp-b2092.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCut82dAtrJeeHzY54NJe8VOYLgO7oOF6E',
    appId: '1:552256631901:web:f006a1b4295818679949b4',
    messagingSenderId: '552256631901',
    projectId: 'healthapp-b2092',
    authDomain: 'healthapp-b2092.firebaseapp.com',
    storageBucket: 'healthapp-b2092.firebasestorage.app',
    measurementId: 'G-N5SNB9N2JR',
  );
}
